[ZPI-26] Login page
Veermove/zpi pull request #14
Opened 2023-10-23 13:58 UTC by gcfbn

2023-10-23 17:49 UTC, Veermove requested changes

2023-10-23 17:49 UTC, Veermove commented on frontend/src/app/i18n/client.ts
> +      setCookie(cookieName, lng, { path: '/' })
so wait we are using cookies to track langauge, so does it need to be path segment?

2023-10-23 17:49 UTC, Veermove commented on frontend/src/app/i18n/locales/en/signin.json
> +    "incorrectEmail": "Incorrect email"
i haven't looked further yet, but is it not missing something like `Login failed, incorrect password or email` ? That case can happen right?

2023-10-23 17:49 UTC, Veermove commented on frontend/src/components/isAuth.tsx
> +import { useEffect } from "react";
This whole file is unused

2023-10-24 16:35 UTC, Remmo1 reviewed
ok

2023-10-24 16:35 UTC, Remmo1 approved these changes

2023-10-25 14:01 UTC, Veermove approved these changes
Looks good, much cleaner components than before

2023-10-25 15:05 UTC, merged